### ISSUE TITLE
Add dark icons for white windows theme

### ISSUE THREAD

**Issue by MuseCat77** [Bigljuse/Bloody7_BatteryIcon#1]
It blends in a bit with the background when the white theme is on\
![image](https://user-images.githubusercontent.com/66839978/227244466-49f92e0f-e15f-48a9-86fe-59f4268e4252.png)

**Comment by Bigljuse** [comment]
Ok, i will add theme selector

**Comment by Bigljuse** [comment]
Done in 0.0.4 prerelease.
